SELECT T.TER_IDENTIFICACAO_EMPRESA,T.TER_CODIGO,F.FIL_NOME,COUNT(*)NUMERO_DE_VEICULOS_TERMINAL FROM GTW_VEICULO_TERMINAL V
JOIN GTW_TERMINAL T ON V.TER_CODIGO=T.TER_CODIGO
JOIN GTW_FILIAL F ON F.FIL_CODIGO=T.FIL_CODIGO
GROUP BY T.TER_IDENTIFICACAO_EMPRESA,T.TER_CODIGO,F.FIL_NOME
ORDER BY 1 ASC;

select * from GTW_VEICULO_TERMINAL where ter_codigo='59';
select * from GTW_USUARIO_TERMINAL where ter_codigo='59';

--NUMERO DE USUARIOS PARA CADA TERMINAL
SELECT T.TER_IDENTIFICACAO_EMPRESA,T.TER_CODIGO,F.FIL_NOME,COUNT(*)NUMERO_DE_USUARIOS_TERMINAL FROM GTW_USUARIO_TERMINAL U
JOIN GTW_TERMINAL T ON U.TER_CODIGO=T.TER_CODIGO
JOIN GTW_FILIAL F ON F.FIL_CODIGO=T.FIL_CODIGO
WHERE F.FIL_NOME LIKE'%Rio Claro%'
GROUP BY T.TER_IDENTIFICACAO_EMPRESA,T.TER_CODIGO,F.FIL_NOME
ORDER BY 1 ASC;


